import { TimestampType } from "./interfaces";
import { Winner } from "./Winner";

export interface SearchClubInfo {
  clubId: string
  name: string;
  trophies: SearchTrophyInfo[];
  isAdmin?: boolean;
}

export interface SearchTrophyInfo {
  trophyId: string;
  name: string;
}

export interface Search {
  uid: string | null;
  clubId: string | null;
  sail: string | null;
  boatName: string | null;
  /** The club information, generated by the firestore function. */
  clubs?: SearchClubInfo[];
  /** Indicates the TTL for when the value should expire. */
  expireAfter?: TimestampType;
}

export interface SearchWithResults extends Search {
  /** The clubs */
  clubs: SearchClubInfo[];
  /** The search results. */
  results: SearchResult[];
}

export type SearchResult = Omit<Winner, "notes" | "created" | "modified" | "boatRef">

export interface SearchResultList {
  page: number;
  /** Indicates the TTL for when the value should expire. */
  expireAfter: TimestampType;
  results: SearchResult[];
}
